apiVersion: tf.galleybytes.com/v1beta1
kind: Terraform
metadata:
  name: {{ .Values.ec2.name }}
spec:
  terraformVersion: {{ .Values.terraform.version }}
  persistentVolumeSize: 500Mi
  keepLatestPodsOnly: true
  setup:
    cleanupDisk: true
  ignoreDelete: false

  {{- if .Values.approval.enabled }}
  requireApproval: true
  {{- end }}

  backend: |-
    terraform {
      backend "kubernetes" {
        secret_suffix    = "{{ .Values.ec2.name }}"
        namespace        = "{{ .Release.Namespace }}"
        in_cluster_config = true
      }
    }

  outputsSecret: "{{ .Values.ec2.name }}-outputs"

  terraformModule:
    inline: |-
      {{ (.Files.Get "files/main.tf") | nindent 6 }}

  taskOptions:
  - for: ["plan", "apply", "plan-delete", "apply-delete"]
    env:
    #  - AWS credentials are intentionally not injected to avoid accidental exposure in logs or outputs.
    # - name: AWS_ACCESS_KEY_ID
    #   valueFrom:
    #     secretKeyRef:
    #       name: {{ .Values.aws.credsSecret }}
    #       key: access-key
    # - name: AWS_SECRET_ACCESS_KEY
    #   valueFrom:
    #     secretKeyRef:
    #       name: {{ .Values.aws.credsSecret }}
    #       key: secret-key
    - name: AWS_REGION
      value: {{ .Values.aws.region }}
    - name: TF_VAR_aws_region
      value: {{ .Values.aws.region }}
    - name: TF_VAR_ec2_name
      value: {{ .Values.ec2.name | quote }}
    - name: TF_VAR_ec2_instance_type
      value: {{ .Values.ec2.instanceType | quote }}