{{- $aws := .Values.aws -}}
{{- $ec2 := .Values.ec2 -}}
{{- $terraform := .Values.terraform -}}
apiVersion: tf.galleybytes.com/v1beta1
kind: Terraform
metadata:
  name: {{ $ec2.name }}
spec:
  terraformVersion: {{ $terraform.version | quote }}
  {{- if .Values.serviceAccount }}
  serviceAccount: {{ .Values.serviceAccount | quote }}
  {{- end }}
  persistentVolumeSize: 500Mi
  keepLatestPodsOnly: true
  setup:
    cleanupDisk: true
  ignoreDelete: false

  {{- if .Values.approval.enabled }}
  requireApproval: true
  {{- end }}

  backend: |-
    terraform {
      backend "kubernetes" {
        secret_suffix     = "{{ $ec2.name }}"
        namespace        = "{{ .Release.Namespace }}"
        in_cluster_config = true
      }
    }

  outputsSecret: "{{ $ec2.name }}-outputs"

  terraformModule:
    inline: |-
      {{ (.Files.Get "files/main.tf") | nindent 6 }}

  taskOptions:
  - for: ["plan", "apply", "plan-delete", "apply-delete"]
    env:
    - name: AWS_REGION
      value: {{ $aws.region | quote }}
    - name: TF_VAR_aws_region
      value: {{ $aws.region | quote }}
    - name: TF_VAR_ec2_name
      value: {{ $ec2.name | quote }}
    - name: TF_VAR_ec2_instance_type
      value: {{ $ec2.instanceType | quote }}
    - name: TF_VAR_credentials_source
      value: {{ $aws.credentialsSource | quote }}
    - name: TF_VAR_vault_kubernetes_auth_role
      value: {{ $aws.vaultKubernetesAuthRole | quote }}
    {{- if eq $aws.credentialsSource "env" }}
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: {{ $aws.credsSecret }}
          key: access-key
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: {{ $aws.credsSecret }}
          key: secret-key
    {{- end }}
    {{- if eq $aws.credentialsSource "vault-static" }}
    - name: TF_VAR_vault_kv_mount
      value: {{ $aws.vaultKvMount | quote }}
    - name: TF_VAR_vault_kv_secret_name
      value: {{ $aws.vaultKvSecretName | quote }}
    - name: TF_VAR_vault_static_access_key_field
      value: {{ $aws.vaultStaticAccessKeyField | quote }}
    - name: TF_VAR_vault_static_secret_key_field
      value: {{ $aws.vaultStaticSecretKeyField | quote }}
    {{- end }}
    {{- if eq $aws.credentialsSource "vault-dynamic" }}
    - name: TF_VAR_vault_aws_backend
      value: {{ $aws.vaultAwsBackend | quote }}
    - name: TF_VAR_vault_aws_role
      value: {{ $aws.vaultAwsRole | quote }}
    - name: TF_VAR_vault_aws_type
      value: {{ $aws.vaultAwsType | quote }}
    {{- end }}